version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: engineering-management-katas-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/seed_katas.sql:/docker-entrypoint-initdb.d/seed_katas.sql:ro

volumes:
  postgres_data: