server:
  port: 8080
spring:
  application:
    name: engineering-management-katas-api
  datasource:
    url: jdbc:postgresql://localhost:5432/engineering_management_katas
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect